### ISSUE TITLE
Restart button doesn't work

### ISSUE THREAD

**Issue by dominik-korsa** [Kode/vscode-electron-debug#1]
- VS Code Version: 1.26.1

Restart button doesn't work. It just does nothing. Stopping the debugging process (with the button on the debug bar) works as expected.

Steps to reproduce:

1. Launch an app in Electron
2. Press the Restart button in the debug bar.

**Comment by RobDangerous** [comment]
Works now via vscode-kha (if you use Kha - otherwise just use a pwa-chrome launch config).
