### ISSUE TITLE
Extension at Marketplace will download and use Electron v4.0.1

### ISSUE THREAD

**Issue by ghost** [Kode/vscode-electron-debug#10]
Hi,

Extension at Marketplace will download and use Electron v4.0.1.
Even with:
```
  "devDependencies": {
    "electron": "^8.0.0"
  }
```
the application is launched with Electron v4.0.1

**Comment by RobDangerous** [comment]
That's because the extension in the marketplace is still an older version (and if you want to modify it yourself put it in runtimeDependencies, vscode doesn't download devDependencies for its extensions).

**Comment by ghost** [comment]
@RobDangerous Hey man. I understand that you first reaction regarding this problem might be PEBCAK but you proposed solution dosen't work. I'm not dooing anyyhing fancy, I'm using Electron Quick Start and my package.json is:
```{
  "name": "electron-quick-start",
  "version": "1.0.0",
  "description": "A minimal Electron application",
  "main": "main.js",
  "scripts": {
    "start": "electron ."
  },
  "repository": "https://github.com/electron/electron-quick-start",
  "keywords": [
    "Electron",
    "quick",
    "start",
    "tutorial",
    "demo"
  ],
  "author": "GitHub",
  "license": "CC0-1.0",
  "Dependencies": {
    "electron": "^8.0.0"
  },
  "devDependencies": {
    "electron": "^8.0.0"
  },
  "runtimeDependencies": {
    "electron": "^8.0.0"
  }
}
```
Still, hitting F5 inside VSCode is launching Electron v4.0.1. Executing `npm start` from commandline will launch electron 8.0.0,

**Comment by RobDangerous** [comment]
That is all as expected. Setting a runtimeDependencies option in your own project does nothing, you can not configure the electron version from outside of the extension.

**Comment by ghost** [comment]
@RobDangerous Alright, I get it. I will wait for the next update of the extension.

BTW: Have you thought about the idea of using currently project package dependencies in order to download and launch a specific version of the Electron?

**Comment by RobDangerous** [comment]
No. The basic setup would probably be easy but then I'd have to test with different Electron versions and that's something I don't want to do.
