### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Krusenstiern** [Kode/vscode-electron-debug#19]
- Issue Type: `Performance`
- Extension Name: `electron-debug`
- Extension Version: `18.11.1`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.44.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Aleks-PC\kodetech.electron-debug-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by RobDangerous** [comment]
You forgot to attach that file.

**Comment by RobDangerous** [comment]
Oh well, nothing we can do then.
