### ISSUE TITLE
Better description in README

### ISSUE THREAD

**Issue by xmedeko** [Kode/vscode-electron-debug#4]
This extension seems interesting, but I miss better explanation what it does. README states: "This is a fork of vscode-chrome-debug which automatically downloads and runs Electron".

First of all, why it downloads Electron? Where it is saves? When the download starts? IMHO this feature is useless.

Apparently, the extension adds new launch `"type": "electron"`. Peering at the code, it tries to solve some problems of Electron debugging. I miss info in README, which problems and how are solved and what params the new type `electron` accepts.

**Comment by RobDangerous** [comment]
Why does that extension seem interesting to you when you consider its only feature useless? The download functionality is literally the most complex addition compared to vscode-chrome-debug, nothing interesting to see here.

**Comment by xmedeko** [comment]
I am sorry, apparently, I do not understand what this extension does and why - why do I need to download electron? That's what's this issue is about: Better description in README , please. Why it downloads Electron? Where it is saved? When the download starts?

**Comment by RobDangerous** [comment]
This extension is clearly not useful for you. That's ok. Let it be.
